"""
LangGraph multi-agent orchestrator.
Defines the Supervisor node and wires up the specialized worker agents.
"""
from typing import Annotated, Any, Dict, List, Literal
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from agents.llm_factory import get_llm
from agents.booking_agent import get_booking_agent
from agents.faq_agent import get_faq_agent
from agents.guest_services_agent import get_guest_services_agent
from agents.escalation_agent import get_escalation_agent
from memory.conversation_memory import get_memory

# ── 1. Define State ───────────────────────────────────────────

class AgentState(TypedDict):
    """The routing state."""
    messages: Annotated[list[BaseMessage], add_messages]
    next: str

# ── 2. Define Supervisor Node ─────────────────────────────────

members = ["BookingAgent", "FAQAgent", "ServicesAgent", "EscalationAgent"]
options = ["FINISH"] + members

system_prompt = (
    "You are a supervisor managing a hotel concierge desk. You converse with guests "
    "and route their requests to the most appropriate specialized agent.\n"
    "Based on the conversation so far, pick the next agent to act. "
    "If the guest's request has been fully answered, or if they are just saying hi/thanks, "
    "you can route to FINISH. When an agent outputs something, it will be relayed to the user.\n\n"
    "Available Agents:\n"
    "- BookingAgent: Helps users with creating, checking, or cancelling room bookings.\n"
    "- FAQAgent: For FAQs, policies, hotel information, or general questions: use the faq_agent_tool to get a grounded answer from the knowledge base\n"
    "- ServicesAgent: Handles in-stay requests like room service or complaints. Also handles fetching past booking history.\n"
    "- EscalationAgent: Handles situations where the guest explicitly asks to talk to a human or is extremely angry.\n\n"
    "Always greet the guest warmly if they just say Hi, and route to FAQAgent to handle generic greeting followups, but usually just route to the right agent.\n"
    "Given the conversation below, who should act next? Respond ONLY with one of these exact words: "
    f"{', '.join(options)}"
)

def supervisor_node(state: AgentState) -> Dict[str, Any]:
    llm = get_llm()
    messages = [SystemMessage(content=system_prompt)] + state["messages"]
    
    # Simple structured output routing
    class Router(TypedDict):
        next: Literal["FINISH", "BookingAgent", "FAQAgent", "ServicesAgent", "EscalationAgent"]

        
    router = llm.with_structured_output(Router)
    result = router.invoke(messages)
    
    # If the LLM failed to match, default to FINISH
    next_node = result["next"] if result and "next" in result else "FINISH"
    return {"next": next_node}

# ── 3. Wire up Worker Nodes ───────────────────────────────────

booking_agent = get_booking_agent()
faq_agent = get_faq_agent()
services_agent = get_guest_services_agent()
escalation_agent = get_escalation_agent()

def _call_agent(agent, state: AgentState) -> Dict[str, Any]:
    """Helper to call an agent and format the return message."""
    result = agent.invoke({"messages": state["messages"]})
    # Return the new messages generated by the agent back to state
    return {"messages": [result["messages"][-1]]}

def booking_node(state: AgentState) -> Dict:
    return _call_agent(booking_agent, state)

def faq_node(state: AgentState) -> Dict:
    return _call_agent(faq_agent, state)

def services_node(state: AgentState) -> Dict:
    return _call_agent(services_agent, state)

def escalation_node(state: AgentState) -> Dict:
    return _call_agent(escalation_agent, state)

# ── 4. Build the Graph ────────────────────────────────────────

workflow = StateGraph(AgentState)

workflow.add_node("Supervisor", supervisor_node)
workflow.add_node("BookingAgent", booking_node)
workflow.add_node("FAQAgent", faq_node)
workflow.add_node("ServicesAgent", services_node)
workflow.add_node("EscalationAgent", escalation_node)

# Workers always report back to END so the user can see their response
workflow.add_edge("BookingAgent", END)
workflow.add_edge("FAQAgent", END)
workflow.add_edge("ServicesAgent", END)
workflow.add_edge("EscalationAgent", END)

# Supervisor decides who goes next, or finishes
workflow.add_conditional_edges(
    "Supervisor",
    lambda x: x["next"],
    {
        "BookingAgent": "BookingAgent",
        "FAQAgent": "FAQAgent",
        "ServicesAgent": "ServicesAgent",
        "EscalationAgent": "EscalationAgent",
        "FINISH": END,
    }
)

workflow.add_edge(START, "Supervisor")

# We compile without a checkpoint saver here because we use CosmosDB to seed state
graph = workflow.compile()

# ── Public entry point ────────────────────────────────────────

def run_planner(user_message: str, conversation_id: str) -> str:
    """
    Main entry point called by the CLI.
    1. Load conversation history from CosmosDB Memory.
    2. Invoke the LangGraph.
    3. Save response and return.
    """
    memory = get_memory(conversation_id)
    
    # Load prior messages
    langchain_messages = []
    for msg in memory.chat_memory.messages:
        if msg.type == "human":
            langchain_messages.append(HumanMessage(content=msg.content))
        else:
            langchain_messages.append(SystemMessage(content=msg.content))  # Treat AI answers as prior systemic context
            
    # Add new user message
    langchain_messages.append(HumanMessage(content=user_message))
    
    # ── DEBUG: Hide internal tool execution optionally ─────────
    # The CLI user just wants the final string.
    
    # Invoke the graph
    final_state = graph.invoke({"messages": langchain_messages})
    
    # Get the final AI message
    final_message = final_state["messages"][-1].content
    
    # Save to CosmosDB
    memory.chat_memory.add_user_message(user_message)
    memory.chat_memory.add_ai_message(final_message)
    
    return final_message
